### PR TITLE
Feature/no bounds sequence

### PR DESCRIPTION
**Pull request by Flast**
Relating to https://github.com/boostorg/fusion/commit/c9ae4fc8869faace8eaec797c9c6d90328832f25, introducing `no_bounds_tag` to be able to out-of-bounds access, like
```cpp
static_assert(result_of::size<NoboundsUserSequence>::value < 10, "");
result_of::at_c<NoboundsUserSequence, 10>::type // no error
```

@jfalcou and @K-ballo, feel free to comment.

Note: This PR is independent from variadics PRs.

### CODE REVIEW

**Comment by djowel** [comment]
Do we really need to introduce a new concept for this? (reading up on c9ae4fc).

**Comment by Flast** [comment]
@jfalcou, Do you still use workaround for `at`? If not, we can simply drop this PR.

**Comment by jfalcou** [comment]
Yes I am

**Comment by Flast** [comment]
@djowel , I think that introducing a new concept is safe way to provide old behaviour for who wants it.
Most users don't use (and don't need) new concept, but specializing under detail namespace is worse than it, isn't it ?

**Comment by djowel** [comment]
Concepts are sacred :-) We can't just add a concept for this purpose. Imagine adding a new concept for STL like this. Specializing under detail namespace is also not good. There should be another solution. I'd even prefer a macro for disabling index range checking, if that's the main issue.

**Comment by Flast** [comment]
> Concepts are sacred :-) We can't just add a concept for this purpose. Imagine adding a new concept for STL like this.

Absolutely.

> I'd even prefer a macro for disabling index range checking, if that's the main issue.

OK, It seems like reasonable. I close and open a new PR.

**Comment by jfalcou** [comment]
a macro make no sense. As a provider of libraries suing fusion, forcing my user to add a macro in their project to have a correct compiling code is rather cumbersome.

I don't see the problem of having a UnboundedRange. It's exactly what the new STL2 based on Eric's range have.

**Comment by djowel** [comment]
OK, UnboundedSequence sounds good. What are the models of UnboundedSequence then? It will be odd to have such a concept without any models included. Without an example of such a sequence, how are we going to test?

**Comment by djowel** [comment]
@Flast,  jfalcou makes a compelling case. First off, I think it's the naming that tripped me off. We can start by renaming to Unbounded Sequence and Unbounded Iterator. I'm not sure how we will deal with the model for it and testing, however.

**Comment by Flast** [comment]
> First off, I think it's the naming that tripped me off. We can start by renaming to Unbounded Sequence and Unbounded Iterator.

Unbounded Sequence/Iterator are good name rather than originals.

> I'm not sure how we will deal with the model for it and testing, however.

I'm confusing the difference of model and concept.

**Comment by djowel** [comment]
> I'm confusing the difference of model and concept.

For example, Random Access Sequence is a concept, fusion::vector is a model of that concept.

**Comment by Flast** [comment]
>  > I'm confusing the difference of model and concept.
>
> For example, Random Access Sequence is a concept, fusion::vector is a model of that concept.

Ah, I see.

> What are the models of UnboundedSequence then? It will be odd to have such a concept without any models included.

Unbounded Sequence is not a standalone concept, user should combine it with a traversability concept (i.e. RandomAccess, Forward, ...). My commit message will help: https://github.com/Flast/fusion/commit/1e21a4eb7a4240a9bdb9304ab03ea5761e8a96a3.
e.g. fusion::vector is a Random Access Sequence, but not a Unbounded Sequence. OTOH, some user sequences are Random Access Sequence and also those are Unbounded Sequence (what @jfalcou wants).

**Comment by djowel** [comment]
> Unbounded Sequence is not a standalone concept, user should combine it with a traversability concept (i.e. RandomAccess, Forward, ...). My commit message will help: Flast@1e21a4e.
> e.g. fusion::vector is a Random Access Sequence, but not a Unbounded Sequence. OTOH, some user sequences are Random Access Sequence and also those are Unbounded Sequence (what @jfalcou wants).

Yes, I know. But we do not have any model for it yet, unlike all the other concepts in fusion. So we can't test and improve on it. Is indexing the only feature it needs? How does UnboundedRange in STL2 look like? Perhaps we should look into that for inspiration.

**Comment by Flast** [comment]
> But we do not have any model for it yet, unlike all the other concepts in fusion. So we can't test and improve on it.

[repetitive_view](http://www.boost.org/doc/libs/1_58_0/libs/fusion/doc/html/fusion/view/repetitive_view.html) seems like a Unbounded Sequence.

**Comment by jfalcou** [comment]
actually the concept we need is maybe different.

We need the sequence to have a size BUT any access out of bound return something (either a default value or w/e else). It is ther eto model the injection in a nD space of a mD obejct where m < n.
So what we need is a way to say here is the size, here's what happens if you at_c out of this size

**Comment by Flast** [comment]
I renamed the concept to Unbounded Sequence/Iterator as suggested by https://github.com/boostorg/fusion/pull/85#issuecomment-114732549.

**Pull request merged**
