### PR TITLE
Post beta merge

### PR DESCRIPTION
**Pull request by Flast**
Boost.regression shows newly added test was passed.

I'll ask release manager to merge this PR, so

DO NOT MERGE UNTIL APPROVED.

### CODE REVIEW

**Comment by jeking3** [comment]
What buggy compiler does this address?

**Comment by Flast** [comment]
> What buggy compiler does this address?

@jeking3 MSVC10/11/12 are: #159 is original issue regarding the regression.

**Comment by Flast** [comment]
OK, approved by Daniel.

**Comment by Flast** [comment]
Note that, no changelog update since the `disable_if` is added in this beta.

**Pull request merged**
