### PR TITLE
Fix gcc 9 deprecated copy warning.

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**

### CODE REVIEW

**Comment by Kojoley** [comment]
Is not #212 supersedes this?

**Comment by Romain-Geissler-1A** [comment]
After re-reading both, I would say no, both are actually required.

**Comment by Kojoley** [comment]
> After re-reading both, I would say no, both are actually required.

I do not understand. What I am not getting the error here https://wandbox.org/permlink/D3tiubVSsaC9OqdH then?

**Comment by Romain-Geissler-1A** [comment]
Indeed you are right. https://en.cppreference.com/w/cpp/language/copy_constructor#Implicitly-declared_copy_constructor reads:

> The generation of the implicitly-defined copy constructor is deprecated if T has a user-defined destructor or user-defined copy assignment operator.

So explicitly deleting the copy assignment does not deprecate the implicitly defined copy constructor.

**Pull request closed without merging**
