### PR TITLE
Enabe CI services

### PR DESCRIPTION
**Pull request by Flast**
This is useful to pre-mergin test.

I'll request admin to enable both of Travis-CI and AppVeyor.

### CODE REVIEW

**Comment by Flast** [comment]
boostorg/admin#137

**Comment by daminetreg** [comment]
Awesome we are gonna be able to use this for our fork as well. :+1:

**Comment by daminetreg** [comment]
Awesome we are gonna be able to use this for our patches as well. :+1:

**Comment by djowel** [comment]
Nice!

**Comment by djowel** [comment]
I'm not quite familiar with this CI services. Feel free to merge when necessary.

**Comment by Flast** [comment]
@djowel , do you have admin access for this repo: can you show "Setting" tab?

**Comment by Flast** [comment]
OK, Peter enabled Travis and made me admin of this repo. I'll configure AppVeyor using my account.

**Comment by pdimov** [comment]
You might want to use https://github.com/boostorg/smart_ptr/blob/develop/.travis.yml as a starting point instead.

**Comment by Flast** [comment]
Got it!

**Comment by Flast** [comment]
OK, now both work well; failures are expected at this time.
@pdimov , many thanks!

**Comment by djowel** [comment]
Thanks for working on this, @Flast ! Thanks too, @pdimov !

**Pull request merged**
