### PR TITLE
#231 Added pfr extension

### PR DESCRIPTION
**Pull request by denzor200**
So, here is my implementation of pfr extension for boost fusion library. This extension may be useful for some boost spirit users.
I am ready to answer any question you may have to facilitate the consideration of this PR. Thank you for attention.

### CODE REVIEW

**Comment by daminetreg** [comment]
Looks interesting 🙂 I have to accustomate myself with pfr first before reviewing here.

**Comment by djowel** [comment]
I haven't inspected... Why are the checks failing?

**Comment by denzor200** [comment]
> I haven't inspected... Why are the checks failing?

Yes! There is some checks failing.. 
All on my side - I'll fix it during this or next week.
But i can't fix AppVeyor-side fails, just like this:
`'cl' is not recognized as an internal or external command`

**Comment by denzor200** [comment]
@djowel i'm done. Appveyor's checks was fixed. Travis was fixed too, but now we cant verify this))
It was tested with boost.spirt.x3 in my project, in my opiniton this extension is good.
You can start to inspect, if you wish.

**Comment by djowel** [comment]
I'll look and study tomorrow

**Comment by denzor200** [comment]
Hello everyone! This PR will be extended in the future. I suppose, we need an alternative way to tell fusion that structure must be serialized by pfr, it's way without 'adapt' macro.
```
#include <iostream>
#include <boost/spirit/home/x3.hpp>
#include <boost/fusion/adapted/pfr.hpp>
 
constexpr std::string_view str = "100 200";
 
struct A
{
    int first;
    int second;
};

/// No BOOST_FUSION_ADAPT_STRUCT here! And no BOOST_FUSION_ADAPT_PFR too..
 
int main()
{
    A rec;
    auto iter = str.begin();
    auto const end = str.end();
    using boost::spirit::x3::int_;
    bool r = boost::spirit::x3::parse(iter, end, int_ >> ' ' >> int_, boost::fusion::pfr(rec));
    std::cout << "done (" << std::boolalpha << (r && iter == end) << ")" << std::endl;
    return 0;
}
```

```
#include <iostream>
#include <boost/spirit/home/x3.hpp>
#include <boost/fusion/adapted/pfr.hpp>

constexpr std::string_view str = "100 200";

struct A
{
    int first;
    int second;
};

boost::spirit::x3::rule<class test, boost::fusion::pfr_reference<A>> const test = "test";
auto const test_def = boost::spirit::x3::int_ >> ' ' >> boost::spirit::x3::int_;
BOOST_SPIRIT_DEFINE(test);

int main()
{
    A rec;
    auto iter = str.begin();
    auto const end = str.end();
    bool r = boost::spirit::x3::parse(iter, end, test, boost::fusion::pfr(rec));
    std::cout << "done (" << std::boolalpha << (r && iter == end) << ")" << std::endl;
    return 0;
}
```

**Comment by djowel** [comment]
All checks have failed? What's up with that?

**Comment by denzor200** [comment]
> Hello everyone! This PR will be extended in the future. I suppose, we need an alternative way to tell fusion that structure must be serialized by pfr, it's way without 'adapt' macro.
> ...
> 

Addition to my previous comment.. Consider this simple fusion-able structure:
```
struct A
{
    int first;
    int second;
    int third;
};

BOOST_FUSION_ADAPT_STRUCT(A, first, second/*, third*/);
```

I suggest giving the user of the library the ability to choose from two ways:
**1. boost::fusion::pfr approach**
```
auto a = A{100, 200, 300};
boost::fusion::for_each(boost::fusion::pfr(a), [](auto val) {
	std::cout << val << " ";
});
```
Will print _"100 200 "_, because `boost::fusion::pfr` is intended to indicate that boost.fusion SHOULD serialize value using boost.pfr library. 


**2. boost::fusion::pfr_fields approach**
```
auto a = A{100, 200, 300};
boost::fusion::for_each(boost::fusion::pfr_fields(a), [](auto val) {
	std::cout << val << " ";
}); 
```
Will print _"100 200 300 "_ because `boost::fusion::pfr_fields` is intended to indicate that boost.fusion MUST serialize value using boost.pfr library. This approach do ignore another ways to serialize value and work only with pfr library.

For a structure that is not fusion-able, it makes no difference which way to choose, because `boost::fusion::pfr` and `boost::fusion::pfr_fields` behave the same in this case - both look to pfr for serialization.

@djowel what do you say about this?
PS Inspired by `boost::pfr::io` && `boost::pfr::io_fields` pair from the pfr library.
https://www.boost.org/doc/libs/1_75_0/doc/html/boost_pfr/tutorial.html#boost_pfr.tutorial.three_ways_of_getting_operators

**Comment by denzor200** [comment]
Duplicate of the https://github.com/boostorg/fusion/pull/243

**Pull request closed without merging**
