### PR TITLE
SFINAE-friendly fusion::fold

### PR DESCRIPTION
**Pull request by Flast**
I overhauled fusion::fold to become SFINAE-friendly; It removes `result_of` hack (i.e. `result_of_with_decltype`).

Also, this PR will resolve [#11606](https://svn.boost.org/trac/boost/ticket/11606).

Tested under GCC 5.1.1, Clang 3.6.2, MSVC 9,10,11 and 12 .

### CODE REVIEW

**Comment by djowel** [comment]
This is very welcome news! I'll go review the code ASAP.

**Comment by Flast** [comment]
What's the current status? Did I miss something?

**Comment by djowel** [comment]
Ok, let's bite the bullet and go for this.

**Comment by Lastique** [comment]
I think merging this PR broke develop recently as it removes |result_of_with_decltype| but not updates preprocessed headers, which still use it. See the errors here:

http://www.boost.org/development/tests/develop/developer/output/teeks99-01b-Ubuntu14-04-64-boost-bin-v2-libs-log-test-attr_attribute_set-test-clang-linux-3-6-debug-threading-multi.html

**Pull request merged**
