### PR TITLE
vector: Simplify assign_sequence

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by djowel** [comment]
Cool @Kojoley !

**Comment by Flast** [comment]
Does fold expr version have any advantage over c++11 version?

**Comment by Flast** [comment]
Hm... I got bad compile time result with GCC 8.

https://gist.github.com/Flast/5d162d339453113c690e9386dc9205f2

**Comment by Kojoley** [comment]
Are the results persistent. How many runs you did?

**Comment by Kojoley** [comment]
My results on GCC 8.2.0 is a bit different, `-DBOOST_NO_CXX17_FOLD_EXPRESSIONS` is about 3% faster to compile, though I have reduced number of arguments from 500 to 256 because I do not have enough memory.

**Comment by Flast** [comment]
> Are the results persistent. How many runs you did?

I run two or three times and paste worst case.

> `-DBOOST_NO_CXX17_FOLD_EXPRESSIONS` is about 3% faster to compile,

Is your case faster than bose of current and fold expr? or which?

**Comment by Kojoley** [comment]
> paste worst case

That was not a good decision. It could be anything that disrupted the result :-)

> Is your case faster than bose of current and fold expr? or which?

secs | commit
---- | ------
25.8 | develop
16.3 | this patch
15.5 | this patch with `-DBOOST_NO_CXX17_FOLD_EXPRESSIONS`

**Comment by Flast** [comment]
>  > paste worst case
>
> That was not a good decision. It could be anything that disrupted the result :-)

But it showed a similar trend even though best case...

**Comment by Kojoley** [comment]
> But it showed a similar trend even though best case...

I cannot say that 205/498/259 is similar to 258/163/155

**Comment by Flast** [comment]
> > But it showed a similar trend even though best case...
> 
> I cannot say that 205/498/259 is similar to 258/163/155

I meant that, in my case, bose of best and worst cases are showed a similar trend

**Comment by Kojoley** [comment]
Ping

**Pull request merged**
