### PR TITLE
Pre 1.67.0 beta merge

### PR DESCRIPTION
**Pull request by Flast**
Closing master branch is scheduled in a week.

### CODE REVIEW

**Comment by Flast** [comment]
I didn't test that how makes an impact on compile time, but at this time the SFINAE expr is placed in template parameter due to msvc's bug, or write SFINAE expr twice...

**Comment by djowel** [comment]
Makes me wonder what all those // $$$ JDG temp $$$ are for. I know I wrote them :-P We should probably remove them is BOOST_FUSION_DONT_USE_PREPROCESSED_FILES is not going to go away.

**Comment by Flast** [comment]
> Makes me wonder what all those // $$$ JDG temp $$$ are for. I know I wrote them :-P We should probably remove them is BOOST_FUSION_DONT_USE_PREPROCESSED_FILES is not going to go away.

Yes, it can be removed without any concern, I remove and push without PR.

**Comment by Flast** [comment]
OK, I merge this PR to next release. Optimizing SFINAE expr is task for next to next release.

**Pull request merged**
